apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus-pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "REPLACE-ME" # TODO Load from environment variable
  - name: maxRetries
    value: "3"
  - name: maxRetryDelay
    value: "5s"
  - name: disableEntityManagement
    value: "false" # Allow Dapr to create topics/queues if needed